export const GET_APPOINTMENTS = '[PROPHYSIO] GET_APPOINTMENTS';
export const GET_APPOINTMENT = '[PROPHYSIO] GET_APPOINTMENT';
export const ADD_APPOINTMENT = '[PROPHYSIO] ADD_APPOINTMENT';
export const UPDATE_APPOINTMENT = '[PROPHYSIO] UPDATE_APPOINTMENT';
export const REMOVE_APPOINTMENT = '[PROPHYSIO] REMOVE_APPOINTMENT';