export const GET_PATIENTS = '[PROPHYSIO] GET_PATIENTS';
export const ADD_PATIENT = '[PROPHYSIO] ADD_PATIENT';
export const CONFIRM_REGISTRATION = '[PROPHYSIO] CONFIRM_REGISTRATION';
export const GET_WAITING_PATIENTS = '[PROPHYSIO] GET_WAITING_PATIENTS';