export const GET_PATIENTS = '[PROPHYSIO] GET_PATIENTS';
export const ADD_PATIENT = '[PROPHYSIO] ADD_PATIENT';
export const REMOVE_PATIENT = '[PROPHYSIO] REMOVE_PATIENT';
export const GET_WAITING_PATIENTS = '[PROPHYSIO] GET_WAITING_PATIENTS';
export const CONFIRM_REGISTRATION_FORM = '[PROPHYSIO] CONFIRM_REGISTRATION_FORM';
export const CONFIRM_INTAKE_FORM = '[PROPHYSIO] CONFIRM_INTAKE_FORM';