exports.ApplicationStatus = {
    PENDING: 'ADD_PATIENT_REQUEST_PENDING',
    ACCEPTED: 'ADD_PATIENT_REQUEST_ACCEPTED'
}

exports.AppointmentStatus = {
    BOOKED: 'APPOINTMENT_BOOKED',
    SHOWED_UP: 'APPOINTMENT_SHOWED_UP',
    NO_SHOW: 'APPOINTMENT_NO_SHOW',
    CANCELLED: 'APPOINTMENT_CANCELLED'
}